spring:
  application:
    name: eurekaserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
server:
  port: 9002
management:
  endpoints:
    web:
      exposure:
        include: '*'
